# Generated by Django 4.0.6 on 2022-07-07 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_email_alter_message_room_alter_message_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
